### ISSUE TITLE
Set view at start position after removing with scroll

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#100]
I guess , after removing with scroll also better will setting view to position at the start selection area,  instead (as now) scrolling further on size selection.

**Comment by nelsam** [comment]
If I understand correctly, the steps to reproduce this are:

1. Select a bunch of text, enough that the start of the selection is outside of the current view.
2. Delete that text.
3. See that the editor does not scroll to the cursor.

Does that summarize the issue fairly well?  If so, this is actually a larger problem I need to fix - the editor isn't automatically scrolling to the cursor in a lot of the cases where it should be.

**Comment by Kvaz1r** [comment]
Yes. It's exactly what I mean.
