### ISSUE TITLE
Сlosing tab with hidden tab invoke panic

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#101]
By hidden I mean that this tab displaced with splitter through the visible border.

for vertical:
`panic: SetSize() called with a negative width. Size:`

for horizontal:
`panic: SetSize() called with a negative height. Size:`

**Comment by nelsam** [comment]
This was a bug in `gxui` related to having only a single split with a weight of 0, resulting in a netweight of 0, resulting in `0/0` as the `frac` value to multiply against the width or height of the splitter layout.

Solved by nelsam/gxui@5d25601
