### ISSUE TITLE
After merging split tabs moved tab produce clone. 

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#107]
### Description

After merging split tabs moved tab produce clone. 

### Steps to reproduce

1. vidar test1.txt test2.txt
2. split view horizontally(or vertically)
3. move test2.txt to test1.txt
4. click on tab which move from , in this example test2.txt

### Actual behavior

1. Appearing clone tab of old tab 
2. Both tabs of text2.txt can't be closed by Ctrl-W (close command).

**Comment by nelsam** [comment]
Ah, I see it.  You *have* to click on the tab to trigger the issue - that's what I didn't understand.  I bet the updated logic to move between splits doesn't handle adding the child correctly; I'll dig in to it.
