### ISSUE TITLE
When I type 'j', a 'j' appears

### ISSUE THREAD

**Issue by apoydence** [nelsam/vidar#11]
'j' should move the cursor to the next line.

**Comment by nelsam** [comment]
Uhm.  No.

**Comment by apoydence** [comment]
...boo...

**Comment by nelsam** [comment]
;)

TBH, I do want to support a form of "vi mode", but I'd rather have it be something more intuitive to those who don't already know vi(m).  But I couldn't resist replying as I did.

**Comment by apoydence** [comment]
But you can't have vidar with vi
