### ISSUE TITLE
Disappearing tab after moving other tab to another split editor. 

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#116]
Maybe related to #110 

### Steps to reproduce

1. When move a tab between split editors don't drop the tab immediately, but wait a few moments(instants). .  

### Actual behavior

![gif1](https://user-images.githubusercontent.com/17313967/35355647-a124fa12-0156-11e8-8beb-ab0d04a0d317.gif)

### Stack trace
log is empty

**Comment by nelsam** [comment]
Could be related to #121 - they both deal with tabs and incorrect layout when dragging with the mouse.
