### ISSUE TITLE
How do I set the GOPATH

### ISSUE THREAD

**Issue by apoydence** [nelsam/vidar#12]
It looks like the GOPATH comes from the shell that it was launched from. Can I set it another way?

**Comment by nelsam** [comment]
GOPATH setup has been added.  When opening a project (ctrl+shift+o), the GOPATH is requested (if the project is in a GOPATH, it should auto-fill the GOPATH directory, so there's a good chance you just need to press "enter"), then it's stored in ~/.config/vidar/projects in yaml format.

I've created #17 to track updating these values.
