### ISSUE TITLE
Incorrect undo after cut command

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#123]
### Description

Incorrect undo after cut command

### Steps to reproduce
1. make several selections
2. cut them (ctrl+x)
3. try undo (ctrl+z) this operation 

### Expected behavior

return to the original state

### Actual behavior

"broken" text

**Comment by Kvaz1r** [comment]
Yes, this behaviour really fixed. But now undo takes only one selection at a time(a bit inconvenient, but no more) and first selection disappear while next one selecting. Disappear in meaning absence backlight.

**Comment by nelsam** [comment]
Yeah, the history needs to be updated a bit so that it understands "blocks" of edits.  I think that's a different problem, though.
