### ISSUE TITLE
ProjectTree became runs in expand form

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#146]
### Description

After recently updates ProjectTree became runs in expand form, is that by design?  

### Steps to reproduce

1. open any file

### Expected behavior
![expected](https://user-images.githubusercontent.com/17313967/47934923-74008880-dee1-11e8-8802-8ab309510f53.jpg)

### Actual behavior
![actual](https://user-images.githubusercontent.com/17313967/47934942-867ac200-dee1-11e8-803d-a66770531cbd.jpg)

**Comment by nelsam** [comment]
I meant to dig in to this at some point - honestly, I don't have a preference either way.  I suppose it doesn't make sense to expand the navigator until you open a project.  I don't really remember what changed to make it default to being open ... maybe it's the code that expands the navigator to the currently open file?

**Comment by Kvaz1r** [comment]
Maybe. I was trying to figure why it happened, but it not so obvious. It's not really important but distracted when opening single file without project.
