### ISSUE TITLE
Incorrect opening of file with space in path. 

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#161]
### Description

Incorrect opening of file with space in path. 

### Steps to reproduce

1. vidar E:/Some folder/file.go E:/test.txt

### Expected behavior

Two tabs with files.

### Actual behavior

Three tabs with files(E:/Some folder/file.go are split).

**Comment by nelsam** [comment]
I believe that this is expected at the command line.  Try quoting the folder with spaces in it: `vidar E:/"Some folder"/file.go E:/test.txt`

**Comment by Kvaz1r** [comment]
Yes quoting works, but notepad can handle path with space. Maybe because it can gets only one file for opening. With few it can be indeterminacy - is it local path or global path with space.
