### ISSUE TITLE
If project directory contains many files it's not relayout immediately after project was selected in navigator.

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#169]
### Description

If project directory contains many files it's not relayout immediately after project was selected in navigator. 

### Steps to reproduce

1. Select project in the navigator where many files

### Expected behavior

Relayout of the navigator. 

### Actual behavior

Relayout happens only when start execute of another command.

**Comment by Kvaz1r** [comment]
Funny, while I debugging the issue found a data race. Not sure if it can be reason of the described behaviour though. 

Data race between watcher goroutine [here](https://github.com/nelsam/vidar/blob/master/navigator/project_tree.go#L158) and main goroutine [here](https://github.com/nelsam/vidar/blob/master/navigator/project_tree.go#L119).

Log:

> WARNING: DATA RACE
> Write at 0x00c00037a850 by goroutine 6:
>   github.com/nelsam/vidar/navigator.(*ProjectTree).SetRoot()
>       T:/libraries/Gopath/src/github.com/nelsam/vidar/navigator/project_tree.go:119 +0x156
> ...
> Previous read at 0x00c00037a850 by goroutine 34:
>   github.com/nelsam/vidar/navigator.(*ProjectTree).watch()
>       T:/libraries/Gopath/src/github.com/nelsam/vidar/navigator/project_tree.go:159 +0x6a
> ...

**Comment by nelsam** [comment]
I believe #173 will solve the issue you're talking about as well as the data race.

**Comment by Kvaz1r** [comment]
Yes, it fixed the issue.
