### ISSUE TITLE
Failure to open a selected project when selected from the project list

### ISSUE THREAD

**Issue by ionrock** [nelsam/vidar#174]
### Description

After adding a project, selecting that project from the project list appears to do nothing. The sidebar does not show the project files and the project list is still displayed with the project highlighted. 

### Steps to reproduce

1. Add a project using File -> add-project
2. Select a folder and go path for the project
3. Click the project listing in sidebar
4. Select the recently added project

### Expected behavior

I expect the sidebar to show the project files, directories and modules.

### Actual behavior

The project list shows the selected project highlighted with no other changes. 

### Stack trace

None

**Comment by nelsam** [comment]
Closing issue.  Please reopen if the issue's still present after #173 .
