### ISSUE TITLE
Horizontal scrollbar doesn't contain thumb after resize. 

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#177]
### Description

Horizontal scrollbar doesn't contain thumb after resize. 

### Steps to reproduce

1. Open file 
2. Resize editor so that horizontal scrollbar must appear

### Expected behavior

Horizontal scrollbar contains thumb. 

### Actual behavior

Horizontal scrollbar doesn't contain thumb.

**Comment by Kvaz1r** [comment]
It's regression from [this commit](https://github.com/nelsam/gxui/commit/9c5693ac75229466ad92338b720b12de399bf189). There is also dependency from size ([here](https://github.com/nelsam/gxui/blob/master/mixins/code_editor.go#L260)  and [here](https://github.com/nelsam/gxui/blob/master/mixins/code_editor.go#L269)) so ScrollPosition need been updated after resize too.

**Comment by nelsam** [comment]
Yep, I see it.  Thanks!  It looks like we need to do a little more checking in that code.

**Comment by Kvaz1r** [comment]
I don't see good fix for it. Or cache for size or ugly reset and restore horizOffset in SetSize:
```
	temp := e.horizOffset
	e.horizOffset = -1
	e.SetHorizOffset(temp)
```

**Comment by Kvaz1r** [comment]
Fixed by https://github.com/nelsam/gxui/pull/24
