### ISSUE TITLE
Goals for 2015

### ISSUE THREAD

**Issue by nelsam** [nelsam/vidar#18]
This is just a task tracker for the next couple of weeks for my own sanity, as well as to set a (somewhat lofty) goal for myself.  Before 2015 ends, I would like to finish:
- [ ] Clean up my fork of GXUI
  - Note: this is mostly because upstream is now unmaintained.  I'm not terribly interested in switching UI libraries, especially when GXUI has gotten me this far, so maintaining a fork seems like my best option.
  - [ ] Ideally, add tests and clean up anything related to the editor
- [ ] Add tests to vidar
- [ ] Add a key binding to run arbitrary commands
  - Most of our commands are currently bound to keys.  Make sure that the commands exist primarily via this "arbitrary command" system, since you should be able to do anything (even commands without key bindings) via the command box.
- [x] Add find/replace logic
  - [ ] Ideally, include regexp
- [x] Add per-package TOC
  - This should relate more closely to a project hierarchy.  Maybe the project view should contain a tree, including packages ... and when a project is selected, a TOC is displayed.  Per-file view would be a separate tab, in this case.
- [x] Polish filesystem notifications
  - Right now, files changing on disk will occasionally cause the editor to crash.  This should be looked in to.
- [x] File/Edit/View menu
- [x] Go Imports / Fmt on write
- [ ] Polish code completions
  - [ ] Detect gocode
  - [ ] Install gocode at user's prompt
  - [x] Filter while typing
  - [ ] Trigger on certain events
    - [x] Typing "."
    - [ ] Pausing for some amount of time (200ms?)
      - Should this just be a delay for any other trigger?
  - [ ] When only one completion is available, prompt in-line (i.e. as highlighted text on the same line as is being typed on)

**Comment by nelsam** [comment]
Whelp.  Yay for shooting for the moon and not even escaping the atmosphere.

I'm getting closer.  `gxui` is a hard nut to crack and I severely underestimated how long it would take me to fully grok that codebase.  But now I'm fixing bugs here and there.

**Comment by ben-clayton** [comment]
Hey there.

I just stumbled across your project. It looks great.

While I might not be able to maintain GXUI, I can still find time to try and help answer any questions you might have. That said, it looks like you've grasped most it already.

I _might_ also be able to find some time to accept pull requests for simple fixes too.

Cheers,
Ben

**Comment by nelsam** [comment]
@ben-clayton Alright, thanks for the offer.  Yeah, I've mostly figured out gxui's basic internals by now, but I'm sure I'll hit other things that I'll want to change here and there.

Some of my changes probably don't make sense as a more general library, but things like changing the offsets of code editor lines to match the tab size, when encountering tab characters, I'll make PRs for.

**Comment by nelsam** [comment]
@ben-clayton Oh, and since I haven't mentioned it before: thanks for making gxui in the first place!  In spite of my "hard nut to crack" whining, actually making use of the library has been a breeze.  In under six months and barely more than 6k lines (counting comments and whitespace), I have a working, semi-stable editor, mostly thanks to gxui.

In case anyone ever starts actually using this editor, you deserve far more credit than I do for its existence.  Whether you want it or not.

**Comment by nelsam** [comment]
Two things are making me close this issue:
1. The advent of go 1.8 and the `plugin` package has put a lot of focus on cleaning up the command/hook/plugin architecture, which has put off much of these goals.
2. The direction of vidar has changed slightly.  Tests are gradually being added as individual components are cleaned up.  There are thoughts about potentially switching to shiny in the future, which would mean cleaning up my gxui fork wouldn't be all that useful.  Things like that.
