### ISSUE TITLE
Vidar doesn't compile

### ISSUE THREAD

**Issue by beoran** [nelsam/vidar#198]
### Description

Vidar doesn't compile for me (from the src.hut repository) 

### Steps to reproduce

```bash
$ go version
go version go1.13.12 linux/amd64
$ go get git.sr.ht/~nelsam/vidar
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../src/go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# git.sr.ht/~nelsam/vidar/setting/config
setting/config/config.go:53:11: undefined: yaml.NewDecoder
setting/config/config.go:56:11: undefined: yaml.NewEncoder
# git.sr.ht/~nelsam/gxui/drivers/gl
../gxui/drivers/gl/driver.go:226:12: assignment mismatch: 2 variables but c.window.Window.GetClipboardString returns 1 values
../gxui/drivers/gl/viewport.go:404:20: cannot use c (type *"github.com/go-gl/glfw/v3.2/glfw".Cursor) as type *"github.com/go-gl/glfw/v3.3/glfw".Cursor in argument to v.window.Window.SetCursor
```

### Expected behavior

Should compile

### Actual behavior

Doesn't.

### Stack trace

See above.

It would probably be a good idea to move vidar to use go modules itself for compilation and dependency management to avoid such problems in the future.

**Comment by Kvaz1r** [comment]
Maybe better raise the issue at st.ht too - https://todo.sr.ht/~nelsam/vidar
It seems that st.ht allowed to create ticket via e-mail, so any account is not requirement.

**Comment by nelsam** [comment]
Thanks for the report!

Yeah, I noticed over the weekend that my `sr.ht` version doesn't look right; I haven't quite had time to fix that yet.  I didn't realize it wasn't compiling, though.

**Comment by nelsam** [comment]
Okay, I think it's all set now.

For reference (and I'll add this to CONTRIBUTING.md eventually):

Modules are definitely not helpful for me.  They introduce far more problems than they avoid.  Typically, I will create version branches to keep the `go.mod` and `go.sum` files in - but with both gxui and vidar being still in a mostly experimental stage, the v0 branches might not help much.  Still, I made them, created `go.mod` and `go.sum`, and tagged initial versions over on sr.ht.

The branches on sr.ht were more out of sync than I expected.  That's been fixed.

I *would* appreciate it if you created issues on `todo.sr.ht` in the future, as @Kvaz1r mentioned; but it's not super important right this minute.  I'm still trying to figure out how to find time to work on vidar in my free time now that I'm a homeowner :laughing: 

I'm going to close this issue; please reopen (here or on todo.sr.ht) if it's still not compiling for you.

**Comment by beoran** [comment]
Thanks, I was able to compile and run vidar.

**Comment by nelsam** [comment]
No problem :smile: 

Just a warning: there are some bugs in the current version that I'm trying to work through.  The biggest hurdle has been performance - it's really difficult to edit large files.  This is a problem with how the horizontal scroll bar and offset is measured in `gxui`, our UI library - I've managed to improve the performance locally, but it makes the horizontal scroll bar ... inconsistent.  I'm working on it.  Very, very slowly; but I *am* working on it.

Most of the other bugs that I haven't gotten to revolve around the search/replace commands, not because they're particularly hard, but because the performance problems are having a much larger effect on my work.
