### ISSUE TITLE
gocode failed under windows

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#60]
After trying use show suggestion get the error:
`Error: gocode failed: exit status 1`
I followed [this answer](http://stackoverflow.com/a/36992477/4651282) and check correct of install gocode. Example work. I was able determinate that it happening because this line: 

```
	cmd.Env = []string{
		"PATH=" + os.Getenv("PATH") + ":" + filepath.Join(p.gopath, "bin"),
		"GOPATH=" + p.gopath,
	}
```
If remove this line gocode return empty answer.

**Comment by nelsam** [comment]
Oh, right, windows uses ";" instead of ":" to separate paths. I'll have to check the os package to see if they have a constant I can use for the separator; otherwise it'll need to go in an os-specific file.

**Comment by nelsam** [comment]
Found it already: [PathListSeparator](https://golang.org/pkg/os/#pkg-constants)

**Comment by Kvaz1r** [comment]
error there are still.

**Comment by nelsam** [comment]
Alright, I'll take a good look soon.  My Windows VMs are being a bit annoying, so I might ask one of my co-workers to take a look at it when they get a chance.
