### ISSUE TITLE
There is not opportunity change disk when open file. 

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#96]
This behaviour appears if open file by corresponding button in file menu(especially when none currently open files). It's not a big problem, but would be more conveniently with this possibility.

**Comment by nelsam** [comment]
Good point.  Linux and BSD have a root structure (i.e. everything starts at `/`), so I didn't even think about that.  I'll have to think of a good way of dealing with that.  I don't want to just add branching code, because there is a very high chance that I'll break it without realizing.
